[package]
name = "dnsnfset"
version = "0.1.0"
authors = ["sorz <me@sorz.org>"]

[dependencies]
libc = "0.2"
dns-parser = "0.8"
log = "0.4"
env_logger = "0.5"
clap = "2.32"

[dependencies.nflog]
git = "https://github.com/sorz/nflog-rs"
