[package]
name = "dnsnfset"
version = "0.2.0"
authors = ["sorz <me@sorz.org>"]
edition = "2021"

[dependencies]
libc = "0.2"
log = "0.4"
env_logger = "0.11"
clap = "4"
mnl = "0.3"
dns-parser = "0.8"
protobuf = "4.36.1-release"
fstrm = { git = "https://github.com/sorz/rust-fstrm/", rev = "5416fa0" }
serde = { version = "1.0", features = ["derive"] }
toml = "1"
anyhow = "1"

[build-dependencies]
bindgen = "0.72"
protobuf-codegen = "4.36.1-release"
